---
name: ProtonMail bridge
version: 3.22.4
slug: pmb
description: Send emails using your ProtonMail account via Bridge v3.x
url: https://github.com/merlindegrote/ha-protonmail-bridge-v3
boot: auto
startup: system
init: false
arch:
    - aarch64
    - amd64
    - armv7
image: ghcr.io/merlindegrote/ha-protonmail-bridge-v3/{arch}
auth_api: true
ports:
    25/tcp: 25
    143/tcp: 143
ports_description:
    25/tcp: SMTP port (forwarded to hydroxide internal port 1025)
    143/tcp: IMAP port (forwarded to hydroxide internal port 1143)
options:
    username: null
    password: null
schema:
    username: str
    password: password
